name = "Zeus Enhanced"
prefix = "zen"
author = "ZEN Team"
mainprefix = "x"
sigversion = 3
version = "1.6.1"
reuse_private_key = false
files = [
    "mod.cpp",
    "logo_zen_ca.paa",
    "logo_zen_small_ca.paa",
    "LICENSE",
    "AUTHORS.txt",
    "README.md"
]
include = ["./include"]

keyname = "{{prefix}}_{{version}}"
signame = "{{prefix}}_{{version}}-{{git \"id 8\"}}"

releasebuild = [
    "@zip @ZEN"
]

[header_exts]
version= "{{git \"id 8\"}}"
